### ISSUE TITLE
Question: Macos compatibility

### ISSUE THREAD

**Issue by beckmx** [rfdonnelly/vsp-router#6]
Hello guys, I was wondering if this is able to compile and run on OSX, I noticed that Apple changed the way IO is managed in the OS with DriverKit and I was wondering if the ports are created as real virtual devices

**Comment by rfdonnelly** [comment]
Hello. I haven't tested this on macOS however this ultimately uses [TTYPort::pair()](https://docs.rs/serialport/latest/serialport/struct.TTYPort.html#method.pair) from the serialport crate to create virtual serial ports which seems to support macOS. If you try this on macOS, let me know how it goes.

**Comment by puhitaku** [comment]
It worked on my MacBook Pro 2021 14-inch w/ macOS Ventura 13.1
Nice! 👍

**Comment by puhitaku** [comment]
I intercepted the communication with vsp-router between my program and an MCU connected with a USB serial port. My program worked and communicated as if nothing had changed.

**Comment by rfdonnelly** [comment]
@puhitaku thank you for the report! I'll have to update the README to reflect.
