### ISSUE TITLE
Whether it is compatible with Windows

### ISSUE THREAD

**Issue by qcjxberin** [rfdonnelly/vsp-router#9]
Whether it is compatible with Windows

**Comment by rfdonnelly** [comment]
The short answer is no, Windows is not supported.  The longer answer is that vsp-router performs two functions, creating virtual serial ports AND creating routes between virtual/physical serial ports.  The routing portion could be made to work for Windows.  The creation of virtual serial ports on Windows isn't straightforward.  I could see adding Windows support for routing in the future but not for virtual serial port creation.

With this, you could use vsp-router for routing and [com0com](https://com0com.sourceforge.net/) for virtual serial port creation.

Alternatively, I think you can use com0com + hub4com (provided by the com0com project) to do what vsp-router does but on Windows.  I've used com0com but haven't tried hub4com.

**Comment by rfdonnelly** [comment]
Windows is now supported as of v1.0.0 with the exception of virtual serial port creation.  The com0com project can be used to replace that functionality.
